CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) UNIQUE NOT NULL,
  reminder_enabled TINYINT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) UNIQUE NOT NULL,
  height VARCHAR(32),
  weight VARCHAR(32),
  goal VARCHAR(255),
  preference VARCHAR(255),
  budget VARCHAR(64),
  shopping_frequency VARCHAR(64),
  mode VARCHAR(64),
  family_size VARCHAR(64),
  family_members TEXT,
  restrictions TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) NOT NULL,
  food_name VARCHAR(255) NOT NULL,
  grams FLOAT DEFAULT 0,
  calories FLOAT DEFAULT 0,
  protein FLOAT DEFAULT 0,
  source VARCHAR(32) DEFAULT 'manual',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(openid),
  INDEX(created_at)
);

CREATE TABLE IF NOT EXISTS checkins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) UNIQUE NOT NULL,
  streak INT DEFAULT 0,
  last_date DATE,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
